"""RDAP API Python SDK — look up domains, IPs, ASNs, nameservers, and entities."""

from ._version import __version__
from .client import AsyncRdapApi, RdapApi
from .exceptions import (
    AuthenticationError,
    GatewayTimeoutError,
    MethodNotAllowedError,
    NotFoundError,
    NotSupportedError,
    PayloadTooLargeError,
    PlanUpgradeRequiredError,
    RateLimitError,
    RdapApiError,
    RequestFailedError,
    ServerError,
    SubscriptionRequiredError,
    TemporarilyUnavailableError,
    UpstreamError,
    ValidationError,
)
from .models import (
    AsnResponse,
    BulkDomainResponse,
    BulkDomainResult,
    BulkDomainSummary,
    Contact,
    Dates,
    DomainResponse,
    Entities,
    EntityAutnum,
    EntityNetwork,
    EntityResponse,
    FieldAvailability,
    IpAddresses,
    IpResponse,
    Meta,
    NameserverResponse,
    PingResponse,
    PublicId,
    Redaction,
    RedactionMethod,
    Registrar,
    Remark,
    TldEntry,
    TldListMeta,
    TldListResponse,
    TldMeta,
    TldResponse,
    TldThresholds,
)

__all__ = [
    "__version__",
    "RdapApi",
    "AsyncRdapApi",
    # Exceptions
    "RdapApiError",
    "AuthenticationError",
    "SubscriptionRequiredError",
    "PlanUpgradeRequiredError",
    "NotFoundError",
    "NotSupportedError",
    "ValidationError",
    "MethodNotAllowedError",
    "PayloadTooLargeError",
    "RequestFailedError",
    "RateLimitError",
    "ServerError",
    "TemporarilyUnavailableError",
    "UpstreamError",
    "GatewayTimeoutError",
    # Models
    "AsnResponse",
    "BulkDomainResponse",
    "BulkDomainResult",
    "BulkDomainSummary",
    "Contact",
    "Dates",
    "DomainResponse",
    "Entities",
    "EntityAutnum",
    "EntityNetwork",
    "EntityResponse",
    "FieldAvailability",
    "IpAddresses",
    "IpResponse",
    "Meta",
    "NameserverResponse",
    "PingResponse",
    "PublicId",
    "Redaction",
    "RedactionMethod",
    "Registrar",
    "Remark",
    "TldEntry",
    "TldListMeta",
    "TldListResponse",
    "TldMeta",
    "TldResponse",
    "TldThresholds",
]
